tstr = "this is string example....wow!!!";
substr = "exam";
print("1. :%d" % tstr.find(substr))
print("2. :%d" % tstr.find(substr, 10))
print("3. :%d" % tstr.find(substr, 20))
print("4. :%d" % tstr.find("Exam"))
print("5. :%d" % tstr.index(substr))
print("6. :%d" % tstr.index(substr, 10))
# print("7. :%d" % tstr.index(substr, 20))

print()
print("1. :%r" % tstr.find(substr))
print("2. :%r" % tstr.find(substr, 10))
print("3. :%r" % tstr.find(substr, 20))
print("4. :%r" % tstr.find("Exam"))
print("5. :%r" % tstr.index(substr))
print("6. :%r" % tstr.index(substr, 10))
# print("7. :%r" % tstr.index(substr, 20))

print()
print("1. :%s" % tstr.find(substr))
print("2. :%s" % tstr.find(substr, 10))
print("3. :%s" % tstr.find(substr, 20))
print("4. :%s" % tstr.find("Exam"))
print("5. :%s" % tstr.index(substr))
print("6. :%s" % tstr.index(substr, 10))
# print("7. :%s" % tstr.index(substr, 20))

print()
print("1. :%c" % tstr.find(substr))
print("2. :%c" % tstr.find(substr, 10))
# print("3. :%c" % tstr.find(substr, 20))
# print("4. :%c" % tstr.find("Exam"))
print("5. :%c" % tstr.index(substr))
print("6. :%c" % tstr.index(substr, 10))
# print("7. :%s" % tstr.index(substr, 20))